"""event due dates and traceability

Revision ID: 46c9ceca9836
Revises: bb6d96f02572
Create Date: 2026-07-15 07:24:39.872327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c9ceca9836'
down_revision: Union[str, None] = 'bb6d96f02572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('target_close_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('product_part_number', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('lot_batch', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('supplier', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('work_order', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('machine', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_events_lot_batch'), 'events', ['lot_batch'], unique=False)
    op.create_index(op.f('ix_events_machine'), 'events', ['machine'], unique=False)
    op.create_index(op.f('ix_events_product_part_number'), 'events', ['product_part_number'], unique=False)
    op.create_index(op.f('ix_events_supplier'), 'events', ['supplier'], unique=False)
    op.create_index(op.f('ix_events_work_order'), 'events', ['work_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_work_order'), table_name='events')
    op.drop_index(op.f('ix_events_supplier'), table_name='events')
    op.drop_index(op.f('ix_events_product_part_number'), table_name='events')
    op.drop_index(op.f('ix_events_machine'), table_name='events')
    op.drop_index(op.f('ix_events_lot_batch'), table_name='events')
    op.drop_column('events', 'machine')
    op.drop_column('events', 'work_order')
    op.drop_column('events', 'supplier')
    op.drop_column('events', 'lot_batch')
    op.drop_column('events', 'product_part_number')
    op.drop_column('events', 'target_close_date')
    # ### end Alembic commands ###
