"""capa entity and capa_events link

Revision ID: bb6d96f02572
Revises: 33c7ae2ac472
Create Date: 2026-07-15 07:19:56.549356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6d96f02572'
down_revision: Union[str, None] = '33c7ae2ac472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('containment_actions', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('root_cause_category', sa.String(length=100), nullable=True),
    sa.Column('rca_method', sa.String(length=50), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventive_action', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('verification_outcome', sa.String(length=20), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capas_id'), 'capas', ['id'], unique=False)
    op.create_index(op.f('ix_capas_organization_id'), 'capas', ['organization_id'], unique=False)
    op.create_index(op.f('ix_capas_owner_id'), 'capas', ['owner_id'], unique=False)
    op.create_index(op.f('ix_capas_root_cause_category'), 'capas', ['root_cause_category'], unique=False)
    op.create_table('capa_events',
    sa.Column('capa_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capa_id'], ['capas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('capa_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capa_events')
    op.drop_index(op.f('ix_capas_root_cause_category'), table_name='capas')
    op.drop_index(op.f('ix_capas_owner_id'), table_name='capas')
    op.drop_index(op.f('ix_capas_organization_id'), table_name='capas')
    op.drop_index(op.f('ix_capas_id'), table_name='capas')
    op.drop_table('capas')
    # ### end Alembic commands ###
